networks:
  common:
    driver: bridge
    ipam:
      config:
        - subnet: 178.18.0.0/16

services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /data
    volumes:
      - ${DB_FOLDER}:/data
    networks:
      common:
        ipv4_address: 178.18.0.2

    hostname: database
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    entrypoint: ["sh", "-c", "cd match_manager/match_manager/web/client && npm run build && cd ../../.. && python -m match_manager"]
    restart: on-failure:3
    depends_on:
      db:
        condition: service_started
        restart: true
    volumes:
      - .:/match_manager
    networks:
      - common
    ports:
      - "${WEBSERVER_PORT}:5000"
    stdin_open: true
